[project]
name = "anthropic-mcp-demo"
version = "0.1.0"
description = "mcp client server quickstart"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.51.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.0",
    "python-dotenv>=1.1.0",
]
